import Image from 'next/image'
import { useEffect } from 'react'
import Head from 'next/head'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'
import { AiFillClockCircle } from 'react-icons/ai'
import Navbar from './components/navbar'
import Footer from './components/footer'
import Style from '../styles/Home.module.css';
import Form from './components/Home/HomeInput';
import Link from 'next/link';
import {FaAngleUp} from 'react-icons/fa'

export default function Home() {




  // window.addEventListener('scroll' , changeBackground);

  useEffect(function mount() {
    const element = document.getElementById("navvbar");
      element.classList.remove("navbg");
      element.classList.remove("indexHeadH1");
   
   
      const onScroll = () => {
      
      if (window.scrollY >= 100) {
        element.classList.add("navbg");
        element.classList.add("indexHeadH1");
      }
      
      else {
        element.classList.remove("navbg");
        element.classList.remove("indexHeadH1");
      }
    }

    window.addEventListener("scroll", onScroll);

    return function unMount() {
      window.removeEventListener("scroll", onScroll);
    };
  });

  return (
    <div className='Home row p-0'>
      <div className='fixed-top transition-all navbg' id="navvbar">
        <Navbar />
      </div>
      <Head>
        <title>LDA::eTicketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>



      <div className={`p-0 ${Style.background}`}>
        <h3 className={` ${Style.ferry}`}> Ferry</h3>
        <div className={`col-11 col-md-11 col-lg-10 col-xl-8 mx-auto ${Style.Form}`}>  <Form /> </div>



        {/* booking time */}

        <div className='col-12 ship-timing text-center '>
          <div className='row justify-evenly'>



            <div className='left col-11 col-md-6 col-lg-2 h-min mb-5 flex flex-col justify-center'>
              <h3>LDA eTicketing</h3>

              <hr />
              <Image src="/img/logo.svg" height="100" width="100" className="cursor-pointer " />
            </div>




            <div className='right col-11 col-md-10  col-lg-8 '>
              <div className='row flex '>


                <div className='col-6 flex flex-col lg:flex-row justify-start lg:justify-between'>
                  <h1 className='text-start'>Limbang</h1>
                  <div >
                    <div className='flex items-center'><AiFillClockCircle /> <p className='m-0 mx-2'>Boarding 13:20</p></div>
                    <div className='flex items-center'><AiFillClockCircle /> <p className='m-0 mx-2'>Departure 13:50</p></div>
                  </div>
                </div>
                <div className='col-6 flex flex-col text-right'>
                  <p><span className='clr font-bold'>Seats Available:</span> 56</p>
                  <p><span className='clr font-bold'>Seats Available Business:</span> 06</p>
                  <p><span className='clr font-bold'>Seats Available Economy:</span> 76</p>
                </div>


                <div className='col-12 col-lg-9 ms-auto mt-2'>
                  <div className='flex justify-between items-center'>
                    <p className='clr m-0'>Economy Class Adult</p>
                    <p className='text-sm m-0'><span className='clr font-bold text-lg'>MYR 25.0</span> Per Person</p>
                  </div>
                  <div className='flex justify-between items-center'>
                    <p className='clr m-0'>Business Class Children (2-11 years old)</p>
                    <p className='text-sm m-0'><span className='clr font-bold text-lg'>MYR 25.0</span> Per Person</p>
                  </div>
                  <div className='flex justify-between items-center'>
                    <p className='clr m-0'>Business Class Adult</p>

                    <p className='text-sm m-0'><span className='clr font-bold text-lg'>MYR 25.0</span> Per Person</p>
                  </div>
                  <div className='flex justify-between items-center'>
                    <p className='clr m-0'>Economy Class Child (2-11 years old)</p>
                    <p className='text-sm m-0'><span className='clr font-bold text-lg'>MYR 25.0</span> Per Person</p>
                  </div>
                  <div className='flex justify-between items-center'>
                    <p className='clr m-0'>Infant below 2 years old</p>
                    <p className='text-sm m-0'><span className='clr font-bold text-lg'>MYR 25.0</span> Per Person</p>
                  </div>
                  <div className='flex mt-4 justify-start'>
                    <button className='btn book'> Book</button>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <Footer />
        
      </div>
    </div>
  )
}
